import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

// ── WiredRelayPayload ─────────────────────────────────────────────────────

/// Decoded SDP + session-id returned from the relay.
class WiredRelayPayload {
  final String sdp;
  final String sessionId;
  const WiredRelayPayload({required this.sdp, required this.sessionId});
}

// ── WiredRelay ────────────────────────────────────────────────────────────

/// Minimal signalling relay built on ntfy.sh (free, anonymous, no sign-up).
///
/// Each WebRTC connection uses two ephemeral topics:
///   `ghm-{relayCode}-o`  → host's SDP offer
///   `ghm-{relayCode}-a`  → client's SDP answer
///
/// SDPs are gzip-compressed + base64url-encoded so they stay within ntfy.sh's
/// 4 KB message limit.  The actual game stream is WebRTC DTLS-encrypted —
/// the relay only carries the one-time handshake SDPs.
///
/// The [relayCode] is a short human-typeable string (8 alphanumeric chars)
/// generated by the host and shared out-of-band with the guest.
class WiredRelay {
  WiredRelay._();

  static const _base = 'https://ntfy.sh';

  static String _offerTopic(String code) => 'ghm-${code.toLowerCase()}-o';
  static String _answerTopic(String code) => 'ghm-${code.toLowerCase()}-a';

  // ── Compression ──────────────────────────────────────────────────────────

  static String _compress(String data) {
    final bytes = GZipCodec().encode(utf8.encode(data));
    return base64Url.encode(bytes);
  }

  static String _decompress(String encoded) {
    final bytes =
        GZipCodec().decode(base64Url.decode(base64Url.normalize(encoded)));
    return utf8.decode(bytes);
  }

  // ── Public API ────────────────────────────────────────────────────────────
  //
  // New signalling model (guest-as-offerer):
  //   • All guests post their SDP offers to  ghm-{roomCode}-o  (shared topic).
  //   • Host monitors that topic and replies on  ghm-{roomCode}-a-{sessionId}
  //     (per-guest answer topic, keyed by the guest's session UUID).
  //
  // This lets every guest use the same room code — no per-guest relay code.

  /// Guest → posts its SDP offer to the shared room offer topic.
  static Future<void> postGuestOffer(
    String roomCode,
    String sessionId,
    String offerSdp,
  ) async {
    final body = jsonEncode({'sdp': _compress(offerSdp), 'sid': sessionId});
    await http
        .post(
          Uri.parse('$_base/${_offerTopic(roomCode)}'),
          headers: {'Content-Type': 'application/json'},
          body: body,
        )
        .timeout(const Duration(seconds: 15));
  }

  /// Host → fetches ALL pending guest offers for [roomCode].
  ///
  /// Returns every message ever posted to the offer topic so the host can
  /// process new session IDs it hasn't seen yet.
  static Future<List<WiredRelayPayload>> fetchAllGuestOffers(
      String roomCode) async {
    return _fetchAll(_offerTopic(roomCode));
  }

  /// Host → posts its SDP answer for a specific guest session.
  static Future<void> postHostAnswer(
    String roomCode,
    String sessionId,
    String answerSdp,
  ) async {
    final answerTopic = '${_answerTopic(roomCode)}-$sessionId';
    final body = jsonEncode({'sdp': _compress(answerSdp), 'sid': sessionId});
    await http
        .post(
          Uri.parse('$_base/$answerTopic'),
          headers: {'Content-Type': 'application/json'},
          body: body,
        )
        .timeout(const Duration(seconds: 15));
  }

  /// Guest → polls for the host's answer for its specific session.
  ///
  /// Returns `null` if the host has not yet posted an answer.
  static Future<WiredRelayPayload?> pollHostAnswer(
    String roomCode,
    String sessionId,
  ) async {
    final answerTopic = '${_answerTopic(roomCode)}-$sessionId';
    return _fetchLatest(answerTopic);
  }

  // ── Internals ─────────────────────────────────────────────────────────────

  /// Returns every message ever posted to [topic] (oldest first).
  static Future<List<WiredRelayPayload>> _fetchAll(String topic) async {
    try {
      final resp = await http
          .get(Uri.parse('$_base/$topic/json?poll=1&since=all'))
          .timeout(const Duration(seconds: 10));
      if (resp.statusCode != 200) return const [];
      if (resp.body.length > 524288) return const [];

      final results = <WiredRelayPayload>[];
      for (final line in resp.body.trim().split('\n')) {
        if (line.isEmpty) continue;
        try {
          final event = jsonDecode(line) as Map<String, dynamic>;
          if (event['event'] != 'message') continue;
          final payload =
              jsonDecode(event['message'] as String) as Map<String, dynamic>;
          final compressed = payload['sdp'] as String?;
          final sid = payload['sid'] as String?;
          if (compressed == null || sid == null) continue;
          results.add(WiredRelayPayload(
            sdp: _decompress(compressed),
            sessionId: sid,
          ));
        } catch (_) {
          continue;
        }
      }
      return results;
    } catch (_) {
      return const [];
    }
  }

  static Future<WiredRelayPayload?> _fetchLatest(String topic) async {
    try {
      final resp = await http
          .get(Uri.parse('$_base/$topic/json?poll=1&since=all'))
          .timeout(const Duration(seconds: 10));
      if (resp.statusCode != 200) return null;

      // Guard against unexpectedly large relay responses (max 512 KB).
      if (resp.contentLength != null && resp.contentLength! > 524288) return null;
      final body = resp.body;
      if (body.length > 524288) return null;

      // ntfy.sh returns newline-delimited JSON events; take the latest message.
      final lines = body.trim().split('\n');
      for (final line in lines.reversed) {
        if (line.isEmpty) continue;
        try {
          final event = jsonDecode(line) as Map<String, dynamic>;
          if (event['event'] != 'message') continue;
          final payload =
              jsonDecode(event['message'] as String) as Map<String, dynamic>;
          final compressed = payload['sdp'] as String?;
          final sid = payload['sid'] as String?;
          if (compressed == null || sid == null) continue;
          return WiredRelayPayload(
            sdp: _decompress(compressed),
            sessionId: sid,
          );
        } catch (_) {
          continue;
        }
      }
    } catch (_) {}
    return null;
  }
}
