import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

// ── WiredRelayPayload ─────────────────────────────────────────────────────

/// Decoded SDP + session-id returned from the relay.
class WiredRelayPayload {
  final String sdp;
  final String sessionId;
  const WiredRelayPayload({required this.sdp, required this.sessionId});
}

// ── WiredRelay ────────────────────────────────────────────────────────────

/// Minimal signalling relay built on ntfy.sh (free, anonymous, no sign-up).
///
/// Each WebRTC connection uses two ephemeral topics:
///   `ghm-{relayCode}-o`  → host's SDP offer
///   `ghm-{relayCode}-a`  → client's SDP answer
///
/// SDPs are gzip-compressed + base64url-encoded so they stay within ntfy.sh's
/// 4 KB message limit.  The actual game stream is WebRTC DTLS-encrypted —
/// the relay only carries the one-time handshake SDPs.
///
/// The [relayCode] is a short human-typeable string (8 alphanumeric chars)
/// generated by the host and shared out-of-band with the guest.
class WiredRelay {
  WiredRelay._();

  static const _base = 'https://ntfy.sh';

  static String _offerTopic(String code) => 'ghm-${code.toLowerCase()}-o';
  static String _answerTopic(String code) => 'ghm-${code.toLowerCase()}-a';

  // ── Compression ──────────────────────────────────────────────────────────

  static String _compress(String data) {
    final bytes = GZipCodec().encode(utf8.encode(data));
    return base64Url.encode(bytes);
  }

  static String _decompress(String encoded) {
    final bytes =
        GZipCodec().decode(base64Url.decode(base64Url.normalize(encoded)));
    return utf8.decode(bytes);
  }

  // ── Public API ────────────────────────────────────────────────────────────

  /// Posts [offerSdp] to the relay under [relayCode].
  static Future<void> postOffer(
    String relayCode,
    String sessionId,
    String offerSdp,
  ) async {
    final body = jsonEncode({'sdp': _compress(offerSdp), 'sid': sessionId});
    await http
        .post(
          Uri.parse('$_base/${_offerTopic(relayCode)}'),
          headers: {'Content-Type': 'application/json'},
          body: body,
        )
        .timeout(const Duration(seconds: 15));
  }

  /// Fetches the latest SDP offer posted for [relayCode].
  ///
  /// Returns `null` if no offer has been posted yet or on error.
  static Future<WiredRelayPayload?> fetchOffer(String relayCode) async {
    return _fetchLatest(_offerTopic(relayCode));
  }

  /// Posts [answerSdp] to the relay under [relayCode].
  static Future<void> postAnswer(
    String relayCode,
    String sessionId,
    String answerSdp,
  ) async {
    final body = jsonEncode({'sdp': _compress(answerSdp), 'sid': sessionId});
    await http
        .post(
          Uri.parse('$_base/${_answerTopic(relayCode)}'),
          headers: {'Content-Type': 'application/json'},
          body: body,
        )
        .timeout(const Duration(seconds: 15));
  }

  /// Checks whether an SDP answer has been posted for [relayCode].
  ///
  /// Returns `null` if no answer has been posted yet or on error.
  static Future<WiredRelayPayload?> pollAnswer(String relayCode) async {
    return _fetchLatest(_answerTopic(relayCode));
  }

  // ── Internals ─────────────────────────────────────────────────────────────

  static Future<WiredRelayPayload?> _fetchLatest(String topic) async {
    try {
      final resp = await http
          .get(Uri.parse('$_base/$topic/json?poll=1&since=all'))
          .timeout(const Duration(seconds: 10));
      if (resp.statusCode != 200) return null;

      // Guard against unexpectedly large relay responses (max 512 KB).
      if (resp.contentLength != null && resp.contentLength! > 524288) return null;
      final body = resp.body;
      if (body.length > 524288) return null;

      // ntfy.sh returns newline-delimited JSON events; take the latest message.
      final lines = body.trim().split('\n');
      for (final line in lines.reversed) {
        if (line.isEmpty) continue;
        try {
          final event = jsonDecode(line) as Map<String, dynamic>;
          if (event['event'] != 'message') continue;
          final payload =
              jsonDecode(event['message'] as String) as Map<String, dynamic>;
          final compressed = payload['sdp'] as String?;
          final sid = payload['sid'] as String?;
          if (compressed == null || sid == null) continue;
          return WiredRelayPayload(
            sdp: _decompress(compressed),
            sessionId: sid,
          );
        } catch (_) {
          continue;
        }
      }
    } catch (_) {}
    return null;
  }
}
